name: task_manager_app
description: "Task manager app using Flutter that allows users to manage their tasks efficiently."

publish_to: 'none' #


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Mohammad AlRefaie Dependencies:
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  lottie: ^3.1.2
  flutter_conditional_rendering: ^2.1.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  flutter_launcher_icons: ^0.13.1
  pull_to_refresh: ^2.0.0
  animate_do: ^3.3.4
  get_it: ^7.7.0
  retrofit: ^4.1.0
  equatable: ^2.0.5

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0

  # Dependencies 4 Testing
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  mocktail: ^1.0.4



flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/login/
    - assets/icons/
    - assets/json/
    - assets/app_icon/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 600
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200

